config/routes.rb
Rails.application.routes.draw do

  root 'contacts#index'

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = Contact.all
	end

	def edit
		@contact = Contact.find(params[:id])
	end

	def update
		@contact = Contact.find(params[:id])
	end

	def new
	end

	def create
		@contact = Contact.new(contact_params)
		@contact.save
		redirect_to @contact
	end

	def show
		@contact = Contact.find(params[:id])
	end

	def destroy
		@contact = Contact.find(params[:id])
		@contact.destroy
	end

	private
		def contact_params
			params.require(:contact).permit(:name, :nomor_hp)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/edit.html.erb
<h2>Edit a contact</h2>

<%= form_for :contact, url: contacts_path do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name, :value => @contact.name %>
	</p>
	<p>
		<%= f.label :nomor_hp %>
		<%= f.text_field :nomor_hp %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<p><%= link_to 'Back to all contacts', contacts_path %></p>

app/views/contacts/index.html.erb
<h2>Listing of all contact</h2>

<table>
	<thead>
		<tr>
			<th>Nama</th>
			<th>Nomor HP</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @contacts.each do |c| %>
		<tr>
			<td><%= c.name %></td>
			<td><%= c.nomor_hp %></td>
			<td>
				<%= link_to 'Edit', edit_contact_path(c) %>
				<%= link_to 'show detail', contact_path(c) %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<p><%= link_to 'add new contact', new_contact_path %></p>

app/views/contacts/new.html.erb
<h2>Create a new contact</h2>

<%= form_for :contact, url: contacts_path do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :nomor_hp %>
		<%= f.text_field :nomor_hp %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<p><%= link_to 'Back to all contacts', contacts_path %></p>

app/views/contacts/show.html.erb
<h2>Show contact</h2>

<table>
	<tr>
		<td>Nama</td>
		<td>
			<strong>
				<%= @contact.name %>
			</strong>
		</td>
	</tr>
	<tr>
		<td>Nomor HP</td>
		<td>
			<strong>
				<%= @contact.nomor_hp %>
			</strong>
		</td>
	</tr>
</table>

<p><%= link_to 'List all contacts', contacts_path %></p>

app/views/home/index.html.erb
<h1>Hello world</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello Ruby On Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>